### ISSUE TITLE
{expansion} to create multiple files

### ISSUE THREAD

**Issue by BarbzYHOOL** [tanrax/terminal-AdvancedNewFile#4]
How do we create multiple files in multiple dirs? or just multiple files? not possible right now

That woul dbe cool

**Comment by tanrax** [comment]
They would be very interesting features. you can do a pull request when you want and I'll include it ;)

**Comment by BarbzYHOOL** [comment]
I dn't do enough python yet, but if I do one day, I will!

**Comment by rissson** [comment]
Taking this one!
