### ISSUE TITLE
Does it exist for Arch/Manjaro?

### ISSUE THREAD

**Issue by blogdemoi** [tanrax/terminal-AdvancedNewFile#6]
Hello,
Does it exist for Arch/Manjaro? I can't find it in the official repos or Aur.
Thank you.

**Comment by tanrax** [comment]
Hello!  As far as I know, it's not uploaded.

 In the background there is no need as it can be installed with a simple pip command.  However, if you dare to create it, I will be happy to add it to the README. Bye ✌🏻
